version: 0.2
phases:
    pre_build:
        commands:
            - echo "Pré Build phase - Exemplo baixar dependencias se fosse necessario"
    build:
        commands:                    
            - echo "permission for gradlew"
            - chmod +x ./gradlew
            - echo "test with gradle"     
            - ./gradlew clean build
            - echo "Building"
            - ./gradlew clean build
    post_build:
        commands:
            - echo "Movendo os arquivos que serão feitos upload"
artifacts:
    files:
        - ROOT.war
            
            
         
