version: 0.2
phases:
    pre_build:
        commands:
            - echo "permission for gradlew"
            - chmod +x ./gradlew
    build:
        commands:                    
            - echo "Building"
            - ./gradlew clean build -x check
    post_build:
        commands:
            - echo "Movendo os arquivos que serão feitos upload"
artifacts:
    files:
        - ROOT.war
            
            
         
