version: 0.2
phases:
    pre_build:
        commands:
            - echo "Pré Build phase - Exemplo baixar dependencias se fosse necessario"
    build:
        commands:
            - echo "Building"
            - chmod +x ./gradlew      
            - ./gradlew clean build
    post_build:
        commands:
            #- echo "Movendo os arquivos que serão feitos upload"
            - cp ./dist/*.war ./ROOT.war #
artifacts:
    files:
        - ROOT.war
            
            
         
