server: 
  port: 80
  
build.name: ${description}
build.version: ${version}

spring:
  datasource:
    url: jdbc:mysql://${DB_HOSTNAME}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
        
        
        DB_HOSTNAME=abc-tech.cta6wmiuzkl6.us-east-2.rds.amazonaws.com
        DB_PORT=3306
        DB_NAME=abc_tech
        DB_USERNAME=admin
        DB_PASSWORD=Fiap1234
    